GET http://localhost:5072/games

###
GET http://localhost:5072/games/1

###
POST http://localhost:5072/games
Content-Type: application/json

{
        "name": "MineCraft",
        "genreId": 2,
        "Price": 99,
        "ReleaseDate": "2016-11-18"
}

###
PUT http://localhost:5072/games/1
Content-Type: application/json

{
        "Name": "MineCraft Changes",
        "GenreId": 1,
        "Price": 26,
        "ReleaseDate": "2020-11-18"
}

###
DELETE http://localhost:5072/games/5